'use client';

import { EventList, PageHeader, StateFlow, jobStatusLabel, stateLabel } from '@/components/ui';
import { useSystem } from '@/store/SystemProvider';

export function AutomaticPage() {
  const { status, currentJob, events, failureTarget, setFailureTarget, startJob, stopJob } = useSystem();
  const running = currentJob?.status === 'RUNNING';
  return <>
    <PageHeader eyebrow="실행 엔진" title="자동 운전" description="작업을 생성하고 인지·실행·검증·회복 전 과정을 관리합니다." action={<div className="action-row"><button className="secondary outline" disabled={running || status.emergencyStop} onClick={() => startJob('SORT')}>귀가 분류 생성</button><button className="primary" disabled={running || status.emergencyStop} onClick={() => startJob('PACK')}>가방 준비 시작</button></div>} />
    <section className="simulation-warning"><i>SIM</i><div><b>시뮬레이션 전용 운전</b><p>이 화면의 명령은 가상 어댑터로만 전달되며 실물 SO-ARM101은 움직이지 않습니다.</p></div><span>모드: 시뮬레이션</span></section>
    <div className="automatic-layout"><div className="auto-main"><section className="panel"><div className="panel-head"><div><p>현재 작업</p><span>실시간 작업 진행 정보</span></div>{currentJob && <span className={`status-badge job-${currentJob.status.toLowerCase()}`}>{jobStatusLabel[currentJob.status]}</span>}</div>{currentJob ? <div className="auto-job-head"><div><small>작업 번호</small><h2>{currentJob.id}</h2></div><div><small>현재 상태</small><strong>{stateLabel[currentJob.currentState]}</strong></div><div><small>진행 물품</small><strong>{currentJob.currentItem ?? '-'}</strong></div><div><small>재시도</small><strong>{currentJob.retryCount} / 2</strong></div></div> : <div className="empty-job compact"><b>생성된 작업이 없습니다</b><p>위 버튼으로 가방 준비 또는 귀가 분류를 시작하세요.</p></div>}<div className="progress-track large"><span style={{ width: `${currentJob?.totalItems ? (currentJob.completedItems / currentJob.totalItems) * 100 : 0}%` }} /></div><StateFlow current={status.currentState} />{running && <button className="stop-job" onClick={stopJob}>현재 작업 정지</button>}</section>
      <section className="panel task-queue"><div className="panel-head"><div><p>물품 작업 대기열</p><span>각 물품의 실행 및 검증 상태</span></div><strong>{currentJob?.completedItems ?? 0} / {currentJob?.totalItems ?? 0}</strong></div>{currentJob?.tasks?.map((task, index) => <div className={`task-row task-${task.status.toLowerCase()}`} key={task.id}><i>{task.status === 'SUCCESS' ? '✓' : index + 1}</i><div><b>{task.itemName}</b><small>{task.destination}으로 이동</small></div><span>{task.status === 'WAITING' ? '대기' : task.status === 'RUNNING' ? '실행 중' : task.status === 'SUCCESS' ? '검증 완료' : '실패'}</span></div>)}{!currentJob && <div className="empty-table">작업을 생성하면 물품 대기열이 표시됩니다.</div>}</section></div>
      <aside className="auto-side"><section className="panel test-controls"><div className="panel-head"><div><p>실패 복구 테스트</p><span>다음 작업 1회에 적용</span></div></div><label><input type="radio" name="failure" checked={failureTarget === 'NONE'} onChange={() => setFailureTarget('NONE')} /> 정상 실행</label><label><input type="radio" name="failure" checked={failureTarget === 'PICK'} onChange={() => setFailureTarget('PICK')} /> 파지 실패 시뮬레이션</label><label><input type="radio" name="failure" checked={failureTarget === 'VERIFY'} onChange={() => setFailureTarget('VERIFY')} /> 검증 실패 시뮬레이션</label><p className="hint">RECOVER 상태를 거쳐 최대 2회까지 재시도합니다.</p></section><section className="panel"><div className="panel-head"><div><p>작업 이벤트</p><span>최근 상태 전환</span></div></div><EventList events={events.filter((event) => !currentJob || !event.jobId || event.jobId === currentJob.id)} limit={8} /></section></aside></div>
  </>;
}
